apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: youtube-dl-hpa
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: youtube-dl # Doit correspondre au nom dans votre deployment.yaml
  minReplicas: 1
  maxReplicas: 6 # Limite haute pour protéger vos 3 serveurs OVH
  metrics:
  - type: Pods
    pods:
      metric:
        name: active_downloads # La métrique exposée par votre handler /metrics
      target:
        type: AverageValue
        averageValue: 2 # Seuil de déclenchement (2 téléchargements en moyenne par Pod)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 # Montée immédiate pour la réactivité SaaS
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300 # Attente de 5 min avant de détruire pour finir les téléchargements longs