apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-dl-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
    # 4. Middleware RateLimit (Syntaxe: namespace-nom@kubernetescrd)
    # Cela lie l'ingress au middleware défini dans ratelimit.yaml
    traefik.ingress.kubernetes.io/router.middlewares: apps-ratelimit@kubernetescrd
spec:
  tls:
    - hosts:
        - flash.dgsynthex.online
      # Traefik va stocker le certificat généré dans ce secret
      secretName: flash-tls-cert 
  rules:
    - host: flash.dgsynthex.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: youtube-dl
                port:
                  number: 80