apiVersion: v1
kind: Service
metadata:
  name: youtube-dl
  namespace: apps
spec:
  selector:
    app: youtube-dl
  ports:
    - name: http        # DÃ©fini pour correspondre au ServiceMonitor
      protocol: TCP
      port: 80
      targetPort: 8080