name: ðŸš€ Auto Version Bumper

on:
  push:
    branches: [ "master" ]
    paths: [ "services/**" , "!version.yaml"]

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }} # Crucial pour dÃ©clencher le Tagger ensuite

      - name: Identify and Bump
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          
          COMMIT_MSG=$(git log -1 --pretty=%B)
          CHANGED_SERVICES=$(git diff --name-only HEAD^ HEAD | grep '^services/' | cut -d/ -f2 | sort -u)

          for SERVICE in $CHANGED_SERVICES; do
            if [ -d "services/$SERVICE" ]; then
              CURRENT_VER=$(yq ".services.$SERVICE" versions.yaml)
              IFS='.' read -r major minor patch <<< "$CURRENT_VER"

              if [[ "$COMMIT_MSG" =~ "!" ]] || [[ "$COMMIT_MSG" == *"BREAKING CHANGE"* ]]; then
                NEW_VER="$((major + 1)).0.0"
              elif [[ "$COMMIT_MSG" =~ ^feat: ]]; then
                NEW_VER="$major.$((minor + 1)).0"
              else
                NEW_VER="$major.$minor.$((patch + 1))"
              fi

              yq -i ".services.$SERVICE = \"$NEW_VER\"" versions.yaml
              echo "Bumping $SERVICE to $NEW_VER"
            fi
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add versions.yaml
          git commit -m "[chore] bump versions [skip ci]" || echo "No changes to commit"
          git push origin master